services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
      POSTGRES_DB: todo
      PGDATA: /data/postgres
    volumes:
      - postgres-data:/data/postgres
    ports:
      - 5432:5432

volumes:
  postgres-data:
